name: Feature request
description: 提议 TDSH 新功能
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 你想通过这个功能解决什么痛点？
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案设计
      description: 你设想的实现方式或交互
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: 其他方案
      description: 你试过的替代方案